// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-AeZUG07hJBesyehaiWep-AC4C8sWKE',
    appId: '1:72044258983:web:db496e30388e6249865d82',
    messagingSenderId: '72044258983',
    projectId: 'chat-app-20e01',
    authDomain: 'chat-app-20e01.firebaseapp.com',
    storageBucket: 'chat-app-20e01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1QiZddIkyPSc6Yx5HOhJAB_X2tzjRcFk',
    appId: '1:72044258983:android:07b9f48d344c4a0c865d82',
    messagingSenderId: '72044258983',
    projectId: 'chat-app-20e01',
    storageBucket: 'chat-app-20e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAy228ek2B8bSmt3nAlOaUDEilKgF1yR8',
    appId: '1:72044258983:ios:92b39eee3be75aea865d82',
    messagingSenderId: '72044258983',
    projectId: 'chat-app-20e01',
    storageBucket: 'chat-app-20e01.appspot.com',
    iosClientId:
        '72044258983-6ff3uam2b4nibgl22ob0b9hk3285qrhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAy228ek2B8bSmt3nAlOaUDEilKgF1yR8',
    appId: '1:72044258983:ios:8ab2866381eb3cee865d82',
    messagingSenderId: '72044258983',
    projectId: 'chat-app-20e01',
    storageBucket: 'chat-app-20e01.appspot.com',
    iosClientId:
        '72044258983-ed92jt3det75aai9c7fnr260o2lpi11h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
